#pragma once

#include "il2cpp.h"

void UniRx_Operators_ZipFunc_object__object__object__object____ctor (UniRx_Operators_ZipFunc_T1__T2__T3__TR__o* __this, Il2CppObject* object, intptr_t method, const MethodInfo_3F04B00* method);
Il2CppObject* UniRx_Operators_ZipFunc_object__object__object__object___Invoke (UniRx_Operators_ZipFunc_T1__T2__T3__TR__o* __this, Il2CppObject* arg1, Il2CppObject* arg2, Il2CppObject* arg3, const MethodInfo_3F04B20* method);
System_IAsyncResult_o* UniRx_Operators_ZipFunc_object__object__object__object___BeginInvoke (UniRx_Operators_ZipFunc_T1__T2__T3__TR__o* __this, Il2CppObject* arg1, Il2CppObject* arg2, Il2CppObject* arg3, System_AsyncCallback_o* callback, Il2CppObject* object, const MethodInfo_3F04EC0* method);
Il2CppObject* UniRx_Operators_ZipFunc_object__object__object__object___EndInvoke (UniRx_Operators_ZipFunc_T1__T2__T3__TR__o* __this, System_IAsyncResult_o* result, const MethodInfo_3F04EF0* method);
void UniRx_Operators_ZipFunc_object__object__object__object__object____ctor (UniRx_Operators_ZipFunc_T1__T2__T3__T4__TR__o* __this, Il2CppObject* object, intptr_t method, const MethodInfo_3F04F00* method);
Il2CppObject* UniRx_Operators_ZipFunc_object__object__object__object__object___Invoke (UniRx_Operators_ZipFunc_T1__T2__T3__T4__TR__o* __this, Il2CppObject* arg1, Il2CppObject* arg2, Il2CppObject* arg3, Il2CppObject* arg4, const MethodInfo_3F04F20* method);
System_IAsyncResult_o* UniRx_Operators_ZipFunc_object__object__object__object__object___BeginInvoke (UniRx_Operators_ZipFunc_T1__T2__T3__T4__TR__o* __this, Il2CppObject* arg1, Il2CppObject* arg2, Il2CppObject* arg3, Il2CppObject* arg4, System_AsyncCallback_o* callback, Il2CppObject* object, const MethodInfo_3F052E0* method);
Il2CppObject* UniRx_Operators_ZipFunc_object__object__object__object__object___EndInvoke (UniRx_Operators_ZipFunc_T1__T2__T3__T4__TR__o* __this, System_IAsyncResult_o* result, const MethodInfo_3F05320* method);
void UniRx_Operators_ZipFunc_object__object__object__object__object__object____ctor (UniRx_Operators_ZipFunc_T1__T2__T3__T4__T5__TR__o* __this, Il2CppObject* object, intptr_t method, const MethodInfo_3F05330* method);
Il2CppObject* UniRx_Operators_ZipFunc_object__object__object__object__object__object___Invoke (UniRx_Operators_ZipFunc_T1__T2__T3__T4__T5__TR__o* __this, Il2CppObject* arg1, Il2CppObject* arg2, Il2CppObject* arg3, Il2CppObject* arg4, Il2CppObject* arg5, const MethodInfo_3F05350* method);
System_IAsyncResult_o* UniRx_Operators_ZipFunc_object__object__object__object__object__object___BeginInvoke (UniRx_Operators_ZipFunc_T1__T2__T3__T4__T5__TR__o* __this, Il2CppObject* arg1, Il2CppObject* arg2, Il2CppObject* arg3, Il2CppObject* arg4, Il2CppObject* arg5, System_AsyncCallback_o* callback, Il2CppObject* object, const MethodInfo_3F05730* method);
Il2CppObject* UniRx_Operators_ZipFunc_object__object__object__object__object__object___EndInvoke (UniRx_Operators_ZipFunc_T1__T2__T3__T4__T5__TR__o* __this, System_IAsyncResult_o* result, const MethodInfo_3F05770* method);
void UniRx_Operators_ZipFunc_object__object__object__object__object__object__object____ctor (UniRx_Operators_ZipFunc_T1__T2__T3__T4__T5__T6__TR__o* __this, Il2CppObject* object, intptr_t method, const MethodInfo_3F05780* method);
Il2CppObject* UniRx_Operators_ZipFunc_object__object__object__object__object__object__object___Invoke (UniRx_Operators_ZipFunc_T1__T2__T3__T4__T5__T6__TR__o* __this, Il2CppObject* arg1, Il2CppObject* arg2, Il2CppObject* arg3, Il2CppObject* arg4, Il2CppObject* arg5, Il2CppObject* arg6, const MethodInfo_3F057A0* method);
System_IAsyncResult_o* UniRx_Operators_ZipFunc_object__object__object__object__object__object__object___BeginInvoke (UniRx_Operators_ZipFunc_T1__T2__T3__T4__T5__T6__TR__o* __this, Il2CppObject* arg1, Il2CppObject* arg2, Il2CppObject* arg3, Il2CppObject* arg4, Il2CppObject* arg5, Il2CppObject* arg6, System_AsyncCallback_o* callback, Il2CppObject* object, const MethodInfo_3F05B80* method);
Il2CppObject* UniRx_Operators_ZipFunc_object__object__object__object__object__object__object___EndInvoke (UniRx_Operators_ZipFunc_T1__T2__T3__T4__T5__T6__TR__o* __this, System_IAsyncResult_o* result, const MethodInfo_3F05BC0* method);
void UniRx_Operators_ZipFunc_object__object__object__object__object__object__object__object____ctor (UniRx_Operators_ZipFunc_T1__T2__T3__T4__T5__T6__T7__TR__o* __this, Il2CppObject* object, intptr_t method, const MethodInfo_3F05BD0* method);
Il2CppObject* UniRx_Operators_ZipFunc_object__object__object__object__object__object__object__object___Invoke (UniRx_Operators_ZipFunc_T1__T2__T3__T4__T5__T6__T7__TR__o* __this, Il2CppObject* arg1, Il2CppObject* arg2, Il2CppObject* arg3, Il2CppObject* arg4, Il2CppObject* arg5, Il2CppObject* arg6, Il2CppObject* arg7, const MethodInfo_3F05BF0* method);
System_IAsyncResult_o* UniRx_Operators_ZipFunc_object__object__object__object__object__object__object__object___BeginInvoke (UniRx_Operators_ZipFunc_T1__T2__T3__T4__T5__T6__T7__TR__o* __this, Il2CppObject* arg1, Il2CppObject* arg2, Il2CppObject* arg3, Il2CppObject* arg4, Il2CppObject* arg5, Il2CppObject* arg6, Il2CppObject* arg7, System_AsyncCallback_o* callback, Il2CppObject* object, const MethodInfo_3F05FF0* method);
Il2CppObject* UniRx_Operators_ZipFunc_object__object__object__object__object__object__object__object___EndInvoke (UniRx_Operators_ZipFunc_T1__T2__T3__T4__T5__T6__T7__TR__o* __this, System_IAsyncResult_o* result, const MethodInfo_3F06030* method);
