#pragma once

#include "il2cpp.h"

void UniRx_Operators_ZipLatestFunc_object__object__object__object____ctor (UniRx_Operators_ZipLatestFunc_T1__T2__T3__TR__o* __this, Il2CppObject* object, intptr_t method, const MethodInfo_3F0A900* method);
Il2CppObject* UniRx_Operators_ZipLatestFunc_object__object__object__object___Invoke (UniRx_Operators_ZipLatestFunc_T1__T2__T3__TR__o* __this, Il2CppObject* arg1, Il2CppObject* arg2, Il2CppObject* arg3, const MethodInfo_3F0A920* method);
System_IAsyncResult_o* UniRx_Operators_ZipLatestFunc_object__object__object__object___BeginInvoke (UniRx_Operators_ZipLatestFunc_T1__T2__T3__TR__o* __this, Il2CppObject* arg1, Il2CppObject* arg2, Il2CppObject* arg3, System_AsyncCallback_o* callback, Il2CppObject* object, const MethodInfo_3F0ACC0* method);
Il2CppObject* UniRx_Operators_ZipLatestFunc_object__object__object__object___EndInvoke (UniRx_Operators_ZipLatestFunc_T1__T2__T3__TR__o* __this, System_IAsyncResult_o* result, const MethodInfo_3F0ACF0* method);
void UniRx_Operators_ZipLatestFunc_object__object__object__object__object____ctor (UniRx_Operators_ZipLatestFunc_T1__T2__T3__T4__TR__o* __this, Il2CppObject* object, intptr_t method, const MethodInfo_3F0AD00* method);
Il2CppObject* UniRx_Operators_ZipLatestFunc_object__object__object__object__object___Invoke (UniRx_Operators_ZipLatestFunc_T1__T2__T3__T4__TR__o* __this, Il2CppObject* arg1, Il2CppObject* arg2, Il2CppObject* arg3, Il2CppObject* arg4, const MethodInfo_3F0AD20* method);
System_IAsyncResult_o* UniRx_Operators_ZipLatestFunc_object__object__object__object__object___BeginInvoke (UniRx_Operators_ZipLatestFunc_T1__T2__T3__T4__TR__o* __this, Il2CppObject* arg1, Il2CppObject* arg2, Il2CppObject* arg3, Il2CppObject* arg4, System_AsyncCallback_o* callback, Il2CppObject* object, const MethodInfo_3F0B0E0* method);
Il2CppObject* UniRx_Operators_ZipLatestFunc_object__object__object__object__object___EndInvoke (UniRx_Operators_ZipLatestFunc_T1__T2__T3__T4__TR__o* __this, System_IAsyncResult_o* result, const MethodInfo_3F0B120* method);
void UniRx_Operators_ZipLatestFunc_object__object__object__object__object__object____ctor (UniRx_Operators_ZipLatestFunc_T1__T2__T3__T4__T5__TR__o* __this, Il2CppObject* object, intptr_t method, const MethodInfo_3F0B130* method);
Il2CppObject* UniRx_Operators_ZipLatestFunc_object__object__object__object__object__object___Invoke (UniRx_Operators_ZipLatestFunc_T1__T2__T3__T4__T5__TR__o* __this, Il2CppObject* arg1, Il2CppObject* arg2, Il2CppObject* arg3, Il2CppObject* arg4, Il2CppObject* arg5, const MethodInfo_3F0B150* method);
System_IAsyncResult_o* UniRx_Operators_ZipLatestFunc_object__object__object__object__object__object___BeginInvoke (UniRx_Operators_ZipLatestFunc_T1__T2__T3__T4__T5__TR__o* __this, Il2CppObject* arg1, Il2CppObject* arg2, Il2CppObject* arg3, Il2CppObject* arg4, Il2CppObject* arg5, System_AsyncCallback_o* callback, Il2CppObject* object, const MethodInfo_3F0B530* method);
Il2CppObject* UniRx_Operators_ZipLatestFunc_object__object__object__object__object__object___EndInvoke (UniRx_Operators_ZipLatestFunc_T1__T2__T3__T4__T5__TR__o* __this, System_IAsyncResult_o* result, const MethodInfo_3F0B570* method);
void UniRx_Operators_ZipLatestFunc_object__object__object__object__object__object__object____ctor (UniRx_Operators_ZipLatestFunc_T1__T2__T3__T4__T5__T6__TR__o* __this, Il2CppObject* object, intptr_t method, const MethodInfo_3F0B580* method);
Il2CppObject* UniRx_Operators_ZipLatestFunc_object__object__object__object__object__object__object___Invoke (UniRx_Operators_ZipLatestFunc_T1__T2__T3__T4__T5__T6__TR__o* __this, Il2CppObject* arg1, Il2CppObject* arg2, Il2CppObject* arg3, Il2CppObject* arg4, Il2CppObject* arg5, Il2CppObject* arg6, const MethodInfo_3F0B5A0* method);
System_IAsyncResult_o* UniRx_Operators_ZipLatestFunc_object__object__object__object__object__object__object___BeginInvoke (UniRx_Operators_ZipLatestFunc_T1__T2__T3__T4__T5__T6__TR__o* __this, Il2CppObject* arg1, Il2CppObject* arg2, Il2CppObject* arg3, Il2CppObject* arg4, Il2CppObject* arg5, Il2CppObject* arg6, System_AsyncCallback_o* callback, Il2CppObject* object, const MethodInfo_3F0B980* method);
Il2CppObject* UniRx_Operators_ZipLatestFunc_object__object__object__object__object__object__object___EndInvoke (UniRx_Operators_ZipLatestFunc_T1__T2__T3__T4__T5__T6__TR__o* __this, System_IAsyncResult_o* result, const MethodInfo_3F0B9C0* method);
void UniRx_Operators_ZipLatestFunc_object__object__object__object__object__object__object__object____ctor (UniRx_Operators_ZipLatestFunc_T1__T2__T3__T4__T5__T6__T7__TR__o* __this, Il2CppObject* object, intptr_t method, const MethodInfo_3F0B9D0* method);
Il2CppObject* UniRx_Operators_ZipLatestFunc_object__object__object__object__object__object__object__object___Invoke (UniRx_Operators_ZipLatestFunc_T1__T2__T3__T4__T5__T6__T7__TR__o* __this, Il2CppObject* arg1, Il2CppObject* arg2, Il2CppObject* arg3, Il2CppObject* arg4, Il2CppObject* arg5, Il2CppObject* arg6, Il2CppObject* arg7, const MethodInfo_3F0B9F0* method);
System_IAsyncResult_o* UniRx_Operators_ZipLatestFunc_object__object__object__object__object__object__object__object___BeginInvoke (UniRx_Operators_ZipLatestFunc_T1__T2__T3__T4__T5__T6__T7__TR__o* __this, Il2CppObject* arg1, Il2CppObject* arg2, Il2CppObject* arg3, Il2CppObject* arg4, Il2CppObject* arg5, Il2CppObject* arg6, Il2CppObject* arg7, System_AsyncCallback_o* callback, Il2CppObject* object, const MethodInfo_3F0BDF0* method);
Il2CppObject* UniRx_Operators_ZipLatestFunc_object__object__object__object__object__object__object__object___EndInvoke (UniRx_Operators_ZipLatestFunc_T1__T2__T3__T4__T5__T6__T7__TR__o* __this, System_IAsyncResult_o* result, const MethodInfo_3F0BE30* method);
