#pragma once

#include "il2cpp.h"

void RootMotion_FinalIK_VRIKCalibrator__RecalibrateScale (RootMotion_FinalIK_VRIK_o* ik, RootMotion_FinalIK_VRIKCalibrator_CalibrationData_o* data, RootMotion_FinalIK_VRIKCalibrator_Settings_o* settings, const MethodInfo* method);
void RootMotion_FinalIK_VRIKCalibrator__RecalibrateScale (RootMotion_FinalIK_VRIK_o* ik, RootMotion_FinalIK_VRIKCalibrator_CalibrationData_o* data, float scaleMlp, const MethodInfo* method);
void RootMotion_FinalIK_VRIKCalibrator__CalibrateScale (RootMotion_FinalIK_VRIK_o* ik, RootMotion_FinalIK_VRIKCalibrator_Settings_o* settings, const MethodInfo* method);
void RootMotion_FinalIK_VRIKCalibrator__CalibrateScale (RootMotion_FinalIK_VRIK_o* ik, float scaleMlp, const MethodInfo* method);
RootMotion_FinalIK_VRIKCalibrator_CalibrationData_o* RootMotion_FinalIK_VRIKCalibrator__Calibrate (RootMotion_FinalIK_VRIK_o* ik, RootMotion_FinalIK_VRIKCalibrator_Settings_o* settings, UnityEngine_Transform_o* headTracker, UnityEngine_Transform_o* bodyTracker, UnityEngine_Transform_o* leftHandTracker, UnityEngine_Transform_o* rightHandTracker, UnityEngine_Transform_o* leftFootTracker, UnityEngine_Transform_o* rightFootTracker, const MethodInfo* method);
void RootMotion_FinalIK_VRIKCalibrator__CalibrateLeg (RootMotion_FinalIK_VRIKCalibrator_Settings_o* settings, UnityEngine_Transform_o* tracker, RootMotion_FinalIK_IKSolverVR_Leg_o* leg, UnityEngine_Transform_o* lastBone, UnityEngine_Vector3_o rootForward, bool isLeft, const MethodInfo* method);
void RootMotion_FinalIK_VRIKCalibrator__Calibrate (RootMotion_FinalIK_VRIK_o* ik, RootMotion_FinalIK_VRIKCalibrator_CalibrationData_o* data, UnityEngine_Transform_o* headTracker, UnityEngine_Transform_o* bodyTracker, UnityEngine_Transform_o* leftHandTracker, UnityEngine_Transform_o* rightHandTracker, UnityEngine_Transform_o* leftFootTracker, UnityEngine_Transform_o* rightFootTracker, const MethodInfo* method);
void RootMotion_FinalIK_VRIKCalibrator__CalibrateLeg (RootMotion_FinalIK_VRIKCalibrator_CalibrationData_o* data, UnityEngine_Transform_o* tracker, RootMotion_FinalIK_IKSolverVR_Leg_o* leg, UnityEngine_Transform_o* lastBone, UnityEngine_Vector3_o rootForward, bool isLeft, const MethodInfo* method);
RootMotion_FinalIK_VRIKCalibrator_CalibrationData_o* RootMotion_FinalIK_VRIKCalibrator__Calibrate (RootMotion_FinalIK_VRIK_o* ik, UnityEngine_Transform_o* centerEyeAnchor, UnityEngine_Transform_o* leftHandAnchor, UnityEngine_Transform_o* rightHandAnchor, UnityEngine_Vector3_o centerEyePositionOffset, UnityEngine_Vector3_o centerEyeRotationOffset, UnityEngine_Vector3_o handPositionOffset, UnityEngine_Vector3_o handRotationOffset, float scaleMlp, const MethodInfo* method);
void RootMotion_FinalIK_VRIKCalibrator__CalibrateHead (RootMotion_FinalIK_VRIK_o* ik, UnityEngine_Transform_o* centerEyeAnchor, UnityEngine_Vector3_o anchorPositionOffset, UnityEngine_Vector3_o anchorRotationOffset, const MethodInfo* method);
void RootMotion_FinalIK_VRIKCalibrator__CalibrateBody (RootMotion_FinalIK_VRIK_o* ik, UnityEngine_Transform_o* pelvisTracker, UnityEngine_Vector3_o trackerPositionOffset, UnityEngine_Vector3_o trackerRotationOffset, const MethodInfo* method);
void RootMotion_FinalIK_VRIKCalibrator__CalibrateHands (RootMotion_FinalIK_VRIK_o* ik, UnityEngine_Transform_o* leftHandAnchor, UnityEngine_Transform_o* rightHandAnchor, UnityEngine_Vector3_o anchorPositionOffset, UnityEngine_Vector3_o anchorRotationOffset, const MethodInfo* method);
void RootMotion_FinalIK_VRIKCalibrator__CalibrateHand (UnityEngine_Transform_o* hand, UnityEngine_Transform_o* forearm, UnityEngine_Transform_o* target, UnityEngine_Transform_o* anchor, UnityEngine_Vector3_o positionOffset, UnityEngine_Vector3_o rotationOffset, bool isLeft, const MethodInfo* method);
UnityEngine_Vector3_o RootMotion_FinalIK_VRIKCalibrator__GuessWristToPalmAxis (UnityEngine_Transform_o* hand, UnityEngine_Transform_o* forearm, const MethodInfo* method);
UnityEngine_Vector3_o RootMotion_FinalIK_VRIKCalibrator__GuessPalmToThumbAxis (UnityEngine_Transform_o* hand, UnityEngine_Transform_o* forearm, const MethodInfo* method);
