#pragma once

#include "il2cpp.h"

void MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0___ctor (MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0_o* __this, const MethodInfo* method);
void MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0___CreateDelegate_b__0 (MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0_o* __this, const MethodInfo* method);
void MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0___CreateDelegate_b__1 (MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0_o* __this, Il2CppObject* o1, const MethodInfo* method);
void MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0___CreateDelegate_b__2 (MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0_o* __this, Il2CppObject* o1, Il2CppObject* o2, const MethodInfo* method);
void MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0___CreateDelegate_b__3 (MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0_o* __this, Il2CppObject* o1, Il2CppObject* o2, Il2CppObject* o3, const MethodInfo* method);
void MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0___CreateDelegate_b__4 (MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0_o* __this, Il2CppObject* o1, Il2CppObject* o2, Il2CppObject* o3, Il2CppObject* o4, const MethodInfo* method);
void MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0___CreateDelegate_b__5 (MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0_o* __this, Il2CppObject* o1, Il2CppObject* o2, Il2CppObject* o3, Il2CppObject* o4, Il2CppObject* o5, const MethodInfo* method);
void MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0___CreateDelegate_b__6 (MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0_o* __this, Il2CppObject* o1, Il2CppObject* o2, Il2CppObject* o3, Il2CppObject* o4, Il2CppObject* o5, Il2CppObject* o6, const MethodInfo* method);
void MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0___CreateDelegate_b__7 (MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0_o* __this, Il2CppObject* o1, Il2CppObject* o2, Il2CppObject* o3, Il2CppObject* o4, Il2CppObject* o5, Il2CppObject* o6, Il2CppObject* o7, const MethodInfo* method);
void MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0___CreateDelegate_b__8 (MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0_o* __this, Il2CppObject* o1, Il2CppObject* o2, Il2CppObject* o3, Il2CppObject* o4, Il2CppObject* o5, Il2CppObject* o6, Il2CppObject* o7, Il2CppObject* o8, const MethodInfo* method);
void MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0___CreateDelegate_b__9 (MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0_o* __this, Il2CppObject* o1, Il2CppObject* o2, Il2CppObject* o3, Il2CppObject* o4, Il2CppObject* o5, Il2CppObject* o6, Il2CppObject* o7, Il2CppObject* o8, Il2CppObject* o9, const MethodInfo* method);
void MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0___CreateDelegate_b__10 (MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0_o* __this, Il2CppObject* o1, Il2CppObject* o2, Il2CppObject* o3, Il2CppObject* o4, Il2CppObject* o5, Il2CppObject* o6, Il2CppObject* o7, Il2CppObject* o8, Il2CppObject* o9, Il2CppObject* o10, const MethodInfo* method);
void MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0___CreateDelegate_b__11 (MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0_o* __this, Il2CppObject* o1, Il2CppObject* o2, Il2CppObject* o3, Il2CppObject* o4, Il2CppObject* o5, Il2CppObject* o6, Il2CppObject* o7, Il2CppObject* o8, Il2CppObject* o9, Il2CppObject* o10, Il2CppObject* o11, const MethodInfo* method);
void MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0___CreateDelegate_b__12 (MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0_o* __this, Il2CppObject* o1, Il2CppObject* o2, Il2CppObject* o3, Il2CppObject* o4, Il2CppObject* o5, Il2CppObject* o6, Il2CppObject* o7, Il2CppObject* o8, Il2CppObject* o9, Il2CppObject* o10, Il2CppObject* o11, Il2CppObject* o12, const MethodInfo* method);
void MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0___CreateDelegate_b__13 (MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0_o* __this, Il2CppObject* o1, Il2CppObject* o2, Il2CppObject* o3, Il2CppObject* o4, Il2CppObject* o5, Il2CppObject* o6, Il2CppObject* o7, Il2CppObject* o8, Il2CppObject* o9, Il2CppObject* o10, Il2CppObject* o11, Il2CppObject* o12, Il2CppObject* o13, const MethodInfo* method);
void MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0___CreateDelegate_b__14 (MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0_o* __this, Il2CppObject* o1, Il2CppObject* o2, Il2CppObject* o3, Il2CppObject* o4, Il2CppObject* o5, Il2CppObject* o6, Il2CppObject* o7, Il2CppObject* o8, Il2CppObject* o9, Il2CppObject* o10, Il2CppObject* o11, Il2CppObject* o12, Il2CppObject* o13, Il2CppObject* o14, const MethodInfo* method);
void MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0___CreateDelegate_b__15 (MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0_o* __this, Il2CppObject* o1, Il2CppObject* o2, Il2CppObject* o3, Il2CppObject* o4, Il2CppObject* o5, Il2CppObject* o6, Il2CppObject* o7, Il2CppObject* o8, Il2CppObject* o9, Il2CppObject* o10, Il2CppObject* o11, Il2CppObject* o12, Il2CppObject* o13, Il2CppObject* o14, Il2CppObject* o15, const MethodInfo* method);
void MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0___CreateDelegate_b__16 (MoonSharp_Interpreter_Interop_EventMemberDescriptor___c__DisplayClass22_0_o* __this, Il2CppObject* o1, Il2CppObject* o2, Il2CppObject* o3, Il2CppObject* o4, Il2CppObject* o5, Il2CppObject* o6, Il2CppObject* o7, Il2CppObject* o8, Il2CppObject* o9, Il2CppObject* o10, Il2CppObject* o11, Il2CppObject* o12, Il2CppObject* o13, Il2CppObject* o14, Il2CppObject* o15, Il2CppObject* o16, const MethodInfo* method);
