#pragma once

#include "il2cpp.h"

System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_object_ (System_IObservable_T__o* source, const MethodInfo_29BB8E0* method);
System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_Unit_ (System_IObservable_T__o* source, const MethodInfo_29BBA10* method);
System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_Pair_int__ (System_IObservable_T__o* source, System_Action_T__o* onNext, const MethodInfo_29BBB40* method);
System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_ValueTuple_Character__GameObject__ (System_IObservable_T__o* source, System_Action_T__o* onNext, const MethodInfo_29BBC50* method);
System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_ValueTuple_object__object__ (System_IObservable_T__o* source, System_Action_T__o* onNext, const MethodInfo_29BBC50* method);
System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_ValueTuple_float__int__ (System_IObservable_T__o* source, System_Action_T__o* onNext, const MethodInfo_29BBD60* method);
System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_ValueTuple_float__Int32Enum__ (System_IObservable_T__o* source, System_Action_T__o* onNext, const MethodInfo_29BBE70* method);
System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_ValueTuple_float__WeaponStyle__ (System_IObservable_T__o* source, System_Action_T__o* onNext, const MethodInfo_29BBE70* method);
System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_AnimationEvent_ (System_IObservable_T__o* source, System_Action_T__o* onNext, const MethodInfo_29BC1A0* method);
System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_Character_ (System_IObservable_T__o* source, System_Action_T__o* onNext, const MethodInfo_29BC1A0* method);
System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_Collision_ (System_IObservable_T__o* source, System_Action_T__o* onNext, const MethodInfo_29BC1A0* method);
System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_int_ (System_IObservable_T__o* source, System_Action_T__o* onNext, const MethodInfo_29BBF80* method);
System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_long_ (System_IObservable_T__o* source, System_Action_T__o* onNext, const MethodInfo_29BC090* method);
System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_object_ (System_IObservable_T__o* source, System_Action_T__o* onNext, const MethodInfo_29BC1A0* method);
System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_Phase_ (System_IObservable_T__o* source, System_Action_T__o* onNext, const MethodInfo_29BC1A0* method);
System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_float_ (System_IObservable_T__o* source, System_Action_T__o* onNext, const MethodInfo_29BC2B0* method);
System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_Unit_ (System_IObservable_T__o* source, System_Action_T__o* onNext, const MethodInfo_29BC3C0* method);
System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_object_ (System_IObservable_T__o* source, System_Action_T__o* onNext, System_Action_Exception__o* onError, const MethodInfo_29BC5E0* method);
System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_Unit_ (System_IObservable_T__o* source, System_Action_T__o* onNext, System_Action_Exception__o* onError, const MethodInfo_29BC6F0* method);
System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_object_ (System_IObservable_T__o* source, System_Action_T__o* onNext, System_Action_o* onCompleted, const MethodInfo_29BC4D0* method);
System_IDisposable_o* UniRx_ObservableExtensions__Subscribe_object_ (System_IObservable_T__o* source, System_Action_T__o* onNext, System_Action_Exception__o* onError, System_Action_o* onCompleted, const MethodInfo_29BC800* method);
System_IDisposable_o* UniRx_ObservableExtensions__SubscribeWithState_bool__ReactiveProperty_bool__ (System_IObservable_T__o* source, UniRx_ReactiveProperty_bool__o* state, System_Action_T__TState__o* onNext, const MethodInfo_29BC8C0* method);
System_IDisposable_o* UniRx_ObservableExtensions__SubscribeWithState_bool__object_ (System_IObservable_T__o* source, Il2CppObject* state, System_Action_T__TState__o* onNext, const MethodInfo_29BC8C0* method);
System_IDisposable_o* UniRx_ObservableExtensions__SubscribeWithState_bool__Selectable_ (System_IObservable_T__o* source, UnityEngine_UI_Selectable_o* state, System_Action_T__TState__o* onNext, const MethodInfo_29BC8C0* method);
System_IDisposable_o* UniRx_ObservableExtensions__SubscribeWithState_object__object_ (System_IObservable_T__o* source, Il2CppObject* state, System_Action_T__TState__o* onNext, const MethodInfo_29BCA50* method);
System_IDisposable_o* UniRx_ObservableExtensions__SubscribeWithState_string__Text_ (System_IObservable_T__o* source, UnityEngine_UI_Text_o* state, System_Action_T__TState__o* onNext, const MethodInfo_29BCA50* method);
System_IDisposable_o* UniRx_ObservableExtensions__SubscribeWithState_Unit__IAsyncReactiveCommand_Unit__ (System_IObservable_T__o* source, UniRx_IAsyncReactiveCommand_Unit__o* state, System_Action_T__TState__o* onNext, const MethodInfo_29BCBE0* method);
System_IDisposable_o* UniRx_ObservableExtensions__SubscribeWithState_Unit__IReactiveCommand_Unit__ (System_IObservable_T__o* source, UniRx_IReactiveCommand_Unit__o* state, System_Action_T__TState__o* onNext, const MethodInfo_29BCBE0* method);
System_IDisposable_o* UniRx_ObservableExtensions__SubscribeWithState_Unit__object_ (System_IObservable_T__o* source, Il2CppObject* state, System_Action_T__TState__o* onNext, const MethodInfo_29BCBE0* method);
System_IDisposable_o* UniRx_ObservableExtensions__SubscribeWithState_object__object_ (System_IObservable_T__o* source, Il2CppObject* state, System_Action_T__TState__o* onNext, System_Action_Exception__TState__o* onError, const MethodInfo_29BCED0* method);
System_IDisposable_o* UniRx_ObservableExtensions__SubscribeWithState_object__object_ (System_IObservable_T__o* source, Il2CppObject* state, System_Action_T__TState__o* onNext, System_Action_TState__o* onCompleted, const MethodInfo_29BCD70* method);
System_IDisposable_o* UniRx_ObservableExtensions__SubscribeWithState_object__object_ (System_IObservable_T__o* source, Il2CppObject* state, System_Action_T__TState__o* onNext, System_Action_Exception__TState__o* onError, System_Action_TState__o* onCompleted, const MethodInfo_29BD030* method);
System_IDisposable_o* UniRx_ObservableExtensions__SubscribeWithState2_object__object__object_ (System_IObservable_T__o* source, Il2CppObject* state1, Il2CppObject* state2, System_Action_T__TState1__TState2__o* onNext, const MethodInfo_29BD0F0* method);
System_IDisposable_o* UniRx_ObservableExtensions__SubscribeWithState2_object__object__object_ (System_IObservable_T__o* source, Il2CppObject* state1, Il2CppObject* state2, System_Action_T__TState1__TState2__o* onNext, System_Action_Exception__TState1__TState2__o* onError, const MethodInfo_29BD400* method);
System_IDisposable_o* UniRx_ObservableExtensions__SubscribeWithState2_object__object__object_ (System_IObservable_T__o* source, Il2CppObject* state1, Il2CppObject* state2, System_Action_T__TState1__TState2__o* onNext, System_Action_TState1__TState2__o* onCompleted, const MethodInfo_29BD290* method);
System_IDisposable_o* UniRx_ObservableExtensions__SubscribeWithState2_object__object__object_ (System_IObservable_T__o* source, Il2CppObject* state1, Il2CppObject* state2, System_Action_T__TState1__TState2__o* onNext, System_Action_Exception__TState1__TState2__o* onError, System_Action_TState1__TState2__o* onCompleted, const MethodInfo_29BD570* method);
System_IDisposable_o* UniRx_ObservableExtensions__SubscribeWithState3_long__object__object__object_ (System_IObservable_T__o* source, Il2CppObject* state1, Il2CppObject* state2, Il2CppObject* state3, System_Action_T__TState1__TState2__TState3__o* onNext, const MethodInfo_29BD640* method);
System_IDisposable_o* UniRx_ObservableExtensions__SubscribeWithState3_object__object__object__object_ (System_IObservable_T__o* source, Il2CppObject* state1, Il2CppObject* state2, Il2CppObject* state3, System_Action_T__TState1__TState2__TState3__o* onNext, const MethodInfo_29BD7F0* method);
System_IDisposable_o* UniRx_ObservableExtensions__SubscribeWithState3_object__object__object__object_ (System_IObservable_T__o* source, Il2CppObject* state1, Il2CppObject* state2, Il2CppObject* state3, System_Action_T__TState1__TState2__TState3__o* onNext, System_Action_Exception__TState1__TState2__TState3__o* onError, const MethodInfo_29BDB20* method);
System_IDisposable_o* UniRx_ObservableExtensions__SubscribeWithState3_object__object__object__object_ (System_IObservable_T__o* source, Il2CppObject* state1, Il2CppObject* state2, Il2CppObject* state3, System_Action_T__TState1__TState2__TState3__o* onNext, System_Action_TState1__TState2__TState3__o* onCompleted, const MethodInfo_29BD9A0* method);
System_IDisposable_o* UniRx_ObservableExtensions__SubscribeWithState3_object__object__object__object_ (System_IObservable_T__o* source, Il2CppObject* state1, Il2CppObject* state2, Il2CppObject* state3, System_Action_T__TState1__TState2__TState3__o* onNext, System_Action_Exception__TState1__TState2__TState3__o* onError, System_Action_TState1__TState2__TState3__o* onCompleted, const MethodInfo_29BDCA0* method);
